[package]
name = "rustnum"
version = "0.1.0"
description = "A library to work with numbers"
authors = ["Andrea Coronese <sixpounder@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
